POST https://prometheus/api/v1/otlp/v1/metrics

###

POST https://listener/events/demogo/evgo HTTP/1.1
Content-Type: application/json

{
    "data": [
       {
            "firstName": "Benita",
            "lastName": "Costa"
        }
    ]
}

###
POST http://localhost:8080/events/m1/evrust HTTP/1.1
Content-Type: application/json

{
    "data": [
       {
            "firstName": "Maria",
            "lastName": "C"
        }
    ]
}

###
POST http://localhost:9595/meta HTTP/1.1
Content-Type: application/json

###

POST http://localhost:9090/api/v1/otlp/v1/metrics