POST http://localhost:8080/events/m1/ev1 HTTP/1.1
Content-Type: application/json

{
    "data": [
       {
            "firstName": "Santhosh Kumar",
            "lastName": "Tekuri"
        }
    ]
}