

POST http://localhost:8080/events/m1/evrust4 HTTP/1.1
Content-Type: application/json

{
    "data": [
       {
            "firstName": "Andres",
            "lastName": "C"
        }
    ]
}

###
POST http://localhost:8080/events/m1/ev2 HTTP/1.1
Content-Type: application/json

{
    "data": [
       {
            "firstName": "Maria",
            "lastName": "C"
        }
    ]
}

###
POST http://localhost:9595/meta HTTP/1.1
Content-Type: application/json

###

POST http://localhost:9090/api/v1/otlp/v1/metrics