sudo rm  /etc/ssl/certs/ctl.pem 
sudo rm  /etc/ssl/certs/repo.pem 
sudo rm  /etc/ssl/certs/recorder.pem 
sudo rm  /etc/ssl/certs/listener.pem 
sudo rm  /etc/ssl/certs/queue.pem 
sudo rm  /etc/ssl/certs/jaeger.pem
sudo rm  /etc/ssl/certs/prometheus.pem
sudo rm  /etc/ssl/certs/exec.pem 
sudo sudo update-ca-certificates