// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: recorder.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Recorder_GetJobExecutions_FullMethodName = "/Recorder/GetJobExecutions"
	Recorder_AddJobExecution_FullMethodName  = "/Recorder/AddJobExecution"
)

// RecorderClient is the client API for Recorder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecorderClient interface {
	GetJobExecutions(ctx context.Context, in *GetJobExecutionsRequest, opts ...grpc.CallOption) (Recorder_GetJobExecutionsClient, error)
	AddJobExecution(ctx context.Context, in *AddJobExecutionRequest, opts ...grpc.CallOption) (*Void, error)
}

type recorderClient struct {
	cc grpc.ClientConnInterface
}

func NewRecorderClient(cc grpc.ClientConnInterface) RecorderClient {
	return &recorderClient{cc}
}

func (c *recorderClient) GetJobExecutions(ctx context.Context, in *GetJobExecutionsRequest, opts ...grpc.CallOption) (Recorder_GetJobExecutionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Recorder_ServiceDesc.Streams[0], Recorder_GetJobExecutions_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &recorderGetJobExecutionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Recorder_GetJobExecutionsClient interface {
	Recv() (*GetJobExecutionsReply, error)
	grpc.ClientStream
}

type recorderGetJobExecutionsClient struct {
	grpc.ClientStream
}

func (x *recorderGetJobExecutionsClient) Recv() (*GetJobExecutionsReply, error) {
	m := new(GetJobExecutionsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recorderClient) AddJobExecution(ctx context.Context, in *AddJobExecutionRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, Recorder_AddJobExecution_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecorderServer is the server API for Recorder service.
// All implementations must embed UnimplementedRecorderServer
// for forward compatibility
type RecorderServer interface {
	GetJobExecutions(*GetJobExecutionsRequest, Recorder_GetJobExecutionsServer) error
	AddJobExecution(context.Context, *AddJobExecutionRequest) (*Void, error)
	mustEmbedUnimplementedRecorderServer()
}

// UnimplementedRecorderServer must be embedded to have forward compatible implementations.
type UnimplementedRecorderServer struct {
}

func (UnimplementedRecorderServer) GetJobExecutions(*GetJobExecutionsRequest, Recorder_GetJobExecutionsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetJobExecutions not implemented")
}
func (UnimplementedRecorderServer) AddJobExecution(context.Context, *AddJobExecutionRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddJobExecution not implemented")
}
func (UnimplementedRecorderServer) mustEmbedUnimplementedRecorderServer() {}

// UnsafeRecorderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecorderServer will
// result in compilation errors.
type UnsafeRecorderServer interface {
	mustEmbedUnimplementedRecorderServer()
}

func RegisterRecorderServer(s grpc.ServiceRegistrar, srv RecorderServer) {
	s.RegisterService(&Recorder_ServiceDesc, srv)
}

func _Recorder_GetJobExecutions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetJobExecutionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecorderServer).GetJobExecutions(m, &recorderGetJobExecutionsServer{stream})
}

type Recorder_GetJobExecutionsServer interface {
	Send(*GetJobExecutionsReply) error
	grpc.ServerStream
}

type recorderGetJobExecutionsServer struct {
	grpc.ServerStream
}

func (x *recorderGetJobExecutionsServer) Send(m *GetJobExecutionsReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Recorder_AddJobExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJobExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecorderServer).AddJobExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recorder_AddJobExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecorderServer).AddJobExecution(ctx, req.(*AddJobExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Recorder_ServiceDesc is the grpc.ServiceDesc for Recorder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recorder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Recorder",
	HandlerType: (*RecorderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddJobExecution",
			Handler:    _Recorder_AddJobExecution_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetJobExecutions",
			Handler:       _Recorder_GetJobExecutions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "recorder.proto",
}
